### ISSUE TITLE
Implement Travis CI to run your tests

### ISSUE THREAD

**Issue by DanielHabib** [robertbernardbrown/Pizza#3]
In order to ensure your tests are run every time you push up a pull request(to make sure you dont break anything) implement Travis CI. https://github.com/marketplace/travis-ci
This issue can be closed after you implement the Travis Badge I'll attach a screen shot
https://github.com/refinery29/piston

After you implement Travis google `how to add Travis CI Badge to Github Repo`

**Comment by DanielHabib** [comment]
![image](https://user-images.githubusercontent.com/8617779/31301489-43ed6f12-aac8-11e7-9eb8-d97ffbe56d2b.png)

**Comment by robertbernardbrown** [comment]
I'm having issues getting the travis file to run correctly. I keep getting an error that version 2.7 can't run and upon investigation found this link that says python isn't supported on OSX: https://github.com/travis-ci/travis-ci/issues/2312

Is this what's holding me back? I don't understand why your files would be able to run and mine aren't since you're using a Mac too @DanielHabib

**Comment by DanielHabib** [comment]
You don't actually have to install Travis, simply creating a `.travis.yml` will have your tests run everytime you push a PR up to github
![image](https://user-images.githubusercontent.com/8617779/31340362-e6690dde-acd3-11e7-86dc-29d9236b8bd8.png)
